### ISSUE TITLE
Run GUI mode

### ISSUE THREAD

**Issue by MohsenSaroughi** [ahernanzl/pyClim-SDM#1]
Hi Dear
when I run gui_mode.py with python .\gui_mode.py, I get an error.
'cp' is not recognized as an internal or external command, operable program, or batch file.
What should I do to fix this issue?
Thank you

**Comment by ahernanzl** [comment]
Dear Mr. Ezraile, 
the software has been initially designed for Linux and you are probably working in a different OS. It should work know.
Your feedback is much appreciatted. 
Best regards,
A. Hernanz
