### ISSUE TITLE
how to downscale the daily air temperature from GCMs

### ISSUE THREAD

**Issue by shiph0326** [ahernanzl/pyClim-SDM#10]

**Comment by ahernanzl** [comment]
Just follow the instructions given in the 'How to use' section at README.md. Do you have any specific problem?

**Comment by shiph0326** [comment]
thank you so much！I just find the maximum and minimum temperature downscale method. how to do daily mean air temperature downscale?

**Comment by ahernanzl** [comment]
Unfortunately that is not an option for the moment, although we are planning on a new release which will include mean temperature as well as other target variables. But that will have to wait a few months probably. In the meantime you can trick the software by naming your mean temperature observations (input_data/hres) as if they were tmax or tmin. That should work just fine as long as you use Transfer Function or Analog methods. For other methods additional adaptations might be needed. Let me know if this workaround worked for you!

**Comment by am97njf** [comment]
Good day. I just wanted you to know that if I want to do quantile mapping and downscaling by CNN, how can I get the code? Actually I downloaded the Py-clim SDM as a zip file which consist of some files, but I didn't find the code.

**Comment by ahernanzl** [comment]
Hi! Most of the code is in the /lib folder

**Comment by shiph0326** [comment]
thank you

**Comment by ahernanzl** [comment]
Now it is possible to downscale mean daily temperature
