### ISSUE TITLE
software 

### ISSUE THREAD

**Issue by am97njf** [ahernanzl/pyClim-SDM#12]
Thanks for your help, how can I get the software which it was mentioned as "pyClim-SDM" in the package?

**Comment by ahernanzl** [comment]
Hi, 
just donwload the package and follow the instructions at Readme.md

**Comment by am97njf** [comment]
I have been downloaded the package and I have done the instructions, but I don't know which part of the code, I should change. I just learned primary level at python, not pro.

**Comment by am97njf** [comment]
Actually I prepare my climatic data and should I change the directory of files which consist of codes?!

**Comment by ahernanzl** [comment]
You don't need to change the code. Go to the src folder and run 'python gui_mode.py'. If you have properly installed the required libraries that should open a window with many options where you can select your method
