### ISSUE TITLE
Pyclim-SDM:variable h in  p_hres_metadata and t_hres_metadata

### ISSUE THREAD

**Issue by SathyaK2022** [ahernanzl/pyClim-SDM#14]
Hi,
I have few queries in using the PyClim-SDM model. The Input_data_template contains two files p_hres_metadata and  t_hres_metadata with the variables id,lon,lat and h. May I know what h stands for and what is its unit . Also,  p_hres_metadata has data for the variable 'h'  and its not given in t_hres_metadata.  So, is it mandatory to include data for h in these metadata files. Kindly clarify in this regard.

**Comment by ahernanzl** [comment]
Hi, 
h stands for height, but it is not mandatory.

**Comment by SathyaK2022** [comment]
Hi,
Thank you so much for the clarification. Whether the package PyClim-SDM (in Spyder) will work with Windows Operating System

**Comment by ahernanzl** [comment]
Hi, 
it has not been tested in Windows, sorry.

**Comment by SathyaK2022** [comment]
Hi, can you help out in fixing this error "DisplayDataArray::getMonGridIdx: couldn't find grid for monGridId(0x00000000)", it displays while running the pyclim-sdm.

**Comment by ahernanzl** [comment]
Hi, 
Are you using your own data or the toy datasets included with the software?

**Comment by SathyaK2022** [comment]
for the toy datasets also the same error is displayed

**Comment by ahernanzl** [comment]
What OS are you using? Have you been able to install all the libraries and versions in the requirements.txt? And when do you get that error exactly?

**Comment by SathyaK2022** [comment]
iam using windows 11 operating system sir,and was able to install all the libraries from requirements.txt

**Comment by ahernanzl** [comment]
I see. Unfortunately pyClim-SDM has been designed for Linux. I would recomend to create an Ubuntu partition and install the software in it.

**Comment by SathyaK2022** [comment]
Thanks for the reply sir

**Comment by SathyaK2022** [comment]
Hi,
we have got few queries while executing pyClim-SDM. 
* grid_res is specified as 3, is the grid resolution should be the same in the hres,reanalysis and model inputs or it can be different
* can you tell the parameters to be edited to run for our domain (eg saf_lat,saf_lon etc)
* what would be the format of the output files and how to interpret it
* a user manual would be highly helpful for us.
Thanks

**Comment by ahernanzl** [comment]
Hi,

Unfortunately there is no user manual so far, as we expect the software to be intuitive enough.

The only parameters to be adapted for a different domain are the grid resolution and the SAF limits (lat up/down and lon left/right).

netCDF files (reanalysis and models) must be in a regular grid with the mentioned resolution and covering at least the specified domain plus a border of one grid box. Is that clear?

Kind regards,
Alfonso

**Comment by SathyaK2022** [comment]
Thanks ,its clear. Also can you mention about the output file format.

**Comment by ahernanzl** [comment]
Sure. The outputs are netCDF files that can be converted to ASCII files with the same format that the input observations (input_data/hres/)

**Comment by ahernanzl** [comment]
By the way, could you provide information about what you are using pyClim-SDM for? Country, region, project, purpose, etc. Thanks!

**Comment by SathyaK2022** [comment]
Hi
Thank you so much for the quick response. It  is used for the regional domain of area 130,058 km² .
In the hres folder, I have my precipitation data at 25 x 25 km resolution and temperature at 100 x 100 km resolution. Can I execute the model with this  different resolution of hres data?
Also, In the reanalysis folder, the data is at 25 x 25 km resolution and 
in the models folder, the data is at 100 x 100 km resolution,
With the above inputs  with different resolution, can i run the pyclim-SDM?
In addition, the default output resolution is denoted as 3, may i know the unit of the output grid resolution?

**Comment by ahernanzl** [comment]
Hi,
The grid resolution is in degrees, and your reanalysis and models must have the same grid resolution.
On the other hand, hres for precipitation and for temperature can be in different locations, and they do not need to be in a regular grid.
What project and contry are you using the software in?

**Comment by SathyaK2022** [comment]
Hi, I am using this model for my research work.
To my knowledge, statistical downscaling is to downscale low resolution model data to high resolution data. So, it is understood that model data resolution will be low(eg. 100km  x 100km). Also, if reanalysis data resolution is high, the downscaling data accuracy will be more ( in my data 25 km x 25 km). If that is the case how can reanalysis and models will have the same grid resolution. Please reply on this regard

**Comment by ahernanzl** [comment]
Generally speaking, the reanalysis is in low resolution and it is used to calibrate the relationships with the high resolution (hres) observations. Then those relationships are applied to low resolution climate models.

**Comment by SathyaK2022** [comment]
> Generally speaking, the reanalysis is in low resolution and it is used to calibrate the relationships with the high resolution (hres) observations. Then those relationships are applied to low resolution climate models.

thanks for the reply. can you please brief, how the historical data of GCM is used in the SDM . (ie) will the relationship between historical GCM and hres  not be considered for calibration?

**Comment by ahernanzl** [comment]
For some methods (Model Output Statistics) historical GCMs are used for calibration, yes. And for all methods, historical GCMs are used for a reference period to compute anomalies

**Comment by SathyaK2022** [comment]
hi,
i was able to run check units,preprocess and missing data check. but while running predictors correlation iam getting the below error, 

![sdm](https://user-images.githubusercontent.com/103311540/195926078-2ceb1518-7bc7-44cf-ad5d-0f6240fe6353.JPG)
can you please help in fixing this error because i checked my input data and data is present at data[10956]

**Comment by ahernanzl** [comment]
Please indicate the range of years available in reanalysis netCDFs, years available at hres files, and your selection for calibration years at the GUI.

**Comment by SathyaK2022** [comment]
Hi,
Thank you so much for the reply.In hres,reanalysis and models - range of years is from 1985 to 2014
calibration years for the above error given as 1985 to 2104
after changing calibration years range to 1986 to 2005, same index error for fetching the last data has been displayed
![sdm1](https://user-images.githubusercontent.com/103311540/195968951-d77bb0fc-9814-47c2-a29e-cb2d31e74a52.jpg)

**Comment by SathyaK2022** [comment]
Hi,
Thank you so much for the reply.In hres,reanalysis and models - range of years is from 1985 to 2014
calibration years for the above error given as 1985 to 201
![sdm1](https://user-images.githubusercontent.com/103311540/195970791-65010c1d-6272-44d4-a427-872f0cdf5b56.jpg)
4
after changing calibration years range to 1986 to 2005, same index error for fetching the last data has been displayed as shown above

**Comment by SathyaK2022** [comment]
Hi,
Thank you so much for the reply.In hres,reanalysis and models - range of years is from 1985 to 2014
calibration years for the above error given as 1985 to 2014
after changing calibration years range to 1986 to 2005, same index error for fetching the last data has been displayed
![sdm1](https://user-images.githubusercontent.com/103311540/195970814-db65f4b1-5850-422c-b825-e75a1c5f6d71.jpg)

**Comment by ahernanzl** [comment]
Could you print the following information at precontrol.py before the line with the error (184 or 206?):
obs.shape
calibration_dates
len(calibration_dates)

And at postpro_lib.py, before line 373:
data.shape
ivalid
len(ivalid)

**Comment by ahernanzl** [comment]
I would also suggest moving to the latest version v3.6 if possible

**Comment by SathyaK2022** [comment]
hi,
Thanks for the suggestions,was able to fix the above error. But now while executing GCM evaluation in the experiment precontrol the below error is displayed
![sdm2](https://user-images.githubusercontent.com/103311540/195983365-a63f740c-5792-4f59-baeb-93a9df195e25.JPG)

And the below error is  diplayed while executing the preprocess,train methods in evaluation experiment
![sdm3](https://user-images.githubusercontent.com/103311540/195983758-e694c48e-819d-4482-97c2-bdb901c48a60.JPG)

**Comment by SathyaK2022** [comment]
hi,
was able to solve the gcm evaluation error, in precontrol.py, GCMs_evaluation_historical() was commented at line 1037.
Thanks

**Comment by ahernanzl** [comment]
Yeah, I was going to tell you that. I'll update the code sorry. And about the other error, it seems to me that you have run the preprocess step with a set of Synoptic Analogy Fields and then they have been changed in the training step. Is that it?

**Comment by SathyaK2022** [comment]
hi,
i have choosen the below Synoptic Analogy Fields and the same has been chosen as predictors for Maximum Temperature,Minimum Temperature and Precipitation
![sdm5](https://user-images.githubusercontent.com/103311540/195987418-9dff1396-f84f-48fc-a08f-e856c5cd83ee.JPG)

**Comment by SathyaK2022** [comment]
using the above, i rerun all the steps in precontrol and the first three steps in evaluation,still i get the same error
![sdm7](https://user-images.githubusercontent.com/103311540/195988049-b0778db5-c3c6-4105-84a7-2dfc3b0b75ef.JPG)

**Comment by ahernanzl** [comment]
That's weird. Please print(nsaf, saf_nlats, saf_nlons) before the line with the error, as well as print(saf_train.shape, W.shape)

**Comment by ahernanzl** [comment]
Also, what is your spatial domain (defined at the GUI) and the grid resolution of the netCDF files?

**Comment by SathyaK2022** [comment]
spatial domain defined at GUI is 0.7 and the netcdf files has the same grid resolution.

**Comment by ahernanzl** [comment]
I mean the limits of the domain (lat up, lat down, lon left, lon right). And please print nsaf, saf_nlats, saf_nlons, saf_train.shape, W.shape. I have no clue so far, W and saf_train should have the same dimensions.

**Comment by SathyaK2022** [comment]
hi,
Thanks for the above reply.i was able to sort out the above errors.

Now, if my hres data contains missing value (-999) in one or more grids for entire time period, i get the following error.
![SDM E1](https://user-images.githubusercontent.com/103311540/198245634-bd6a694b-9966-42b0-b87f-d238a8afd749.JPG)
![SDM E2](https://user-images.githubusercontent.com/103311540/198245740-d1300852-82b3-40a4-9eb2-40a119e8f234.JPG)

Kindly help me to sort out the above error

**Comment by SathyaK2022** [comment]
Also whether the model will work with hres data (pr,tasmax and tasmin) containing missing value(-999) in one or more grids for the entire time period .
Thanks

**Comment by ahernanzl** [comment]
Hello, 
you will have to remove those points from your hres, sorry. If they contain no data, they cannot be used. 
And about the problem at line 194 of precontrol.py, could you please print(X.shape, y.shape) before and after lines 187-188 (X = X[ivalid] and y=y[ivalid])?

**Comment by SathyaK2022** [comment]
hi,
Thanks for the reply. if the grid points with no data is removed, then it becomes an unstructured grid. So, can you help in plotting the unstructured netcdf data onto a spatial map

**Comment by ahernanzl** [comment]
Hi,
For pyClim-SDM, observations (hres) are a list of points (1D), not a regular 2D grid. So removing those empty points makes no difference. pyClim-SDM plots maps (among other figures) of these 1D unstructured datasets, through the map() function of the /lib/plot.py file. Hope that helps!

**Comment by SathyaK2022** [comment]
Hi,
I am trying to convert the netcdf files in projections folder(before bias correction) to ascii files, can you please help me out .

**Comment by ahernanzl** [comment]
Are you having any problem?

**Comment by SathyaK2022** [comment]
HI,
In the pyclim-SDM manual it is given as ,"When netCDFs are converted to ASCII files, two new folders are generated:
EVALUATION_ASCII and PROJECTIONS_ASCII". But these two folders are not generated for me.

**Comment by ahernanzl** [comment]
And do those folders exist without '_ASCII'?

**Comment by SathyaK2022** [comment]
Thanks for the reply. I have selected "no" in the bias correction option and the Projections folders with ASCII was created

**Comment by SathyaK2022** [comment]
Hi,
While Using pyclim for Relative Humidity with the following selection,
![image](https://user-images.githubusercontent.com/103311540/205316621-6ad1019c-b4e3-4d0b-8fd3-2c88ca1b0750.png)
i have got a message as displayed below, 
![image](https://user-images.githubusercontent.com/103311540/205316798-b329fc65-91c5-49e8-af73-35ca14bd3bc5.png)
relative humidity sfc not available either directly or indirectly. But i have given hurs files in hres, and hurs and hur in models and r in reanalysis.  Can you please help me to rectify this message and guide to proceed with downscaling of relative humidity

**Comment by ahernanzl** [comment]
Make sure that you have defined the variable name the same way it is in the netCDF files (in the filename and inside the file). Is that it?

**Comment by SathyaK2022** [comment]
Yes sir ,i have defined the same way.

**Comment by geethar123** [comment]
Sir,
With reference to relative humidity, hurs is the name defined for hres data, but for model and reanalysis, it is mentioned as hur. The hurs variable is defined for near surface relative humidity for model and reanalysis name for it is not included.  But, while checking the code, relative humidity is declared as hurs. Kindly clarify it.

**Comment by ahernanzl** [comment]
Hello,
See the 'Domain' tab. There you have to define the name used by your models and reanalysis for hurs. By default hurs name is not defined for reanalysis because the included dataset (ERA5) has no hurs. If your reanalysis has no hurs either, an alternative way to get it is from other humidity inidcators (huss, td..)

**Comment by geethar123** [comment]
Thank you for the reply sir.
Here, the confusion is between hurs and hur
hres - Relative humidity - hurs
reanalysis - Relative humidity - r
model - Relative humidity - hur
Also,
model - Near surface relative humidity - hurs
So, we have used: hres - hurs, model - hur and reanalysis - r for downscaling relative humidity
But, in the coding, relative humidity is calculated using hurs of model. It doesn't include hur (model) and r (reanalysis).
Kindly give suggestion in this regard.

**Comment by ahernanzl** [comment]
I'm sorry but I don't understand the problem. Can you send a screenshot of you Domain tab, and of your filenames for reanalysis and models?

**Comment by geethar123** [comment]
Sir,
To downscale the relative humidity with direct predictors, may i know the required relative humidity file with default domain names.

**Comment by ahernanzl** [comment]
Hi, 
You just need to define the name at the Domain tab of the GUI the same way it is defined at you netCDF files.

**Comment by geethar123** [comment]
Sir,
I have attached the domain tab in which the relative humidity is defined as hurs. I have also attached the png of model and reanalysis data in netcdf file. 
But while running the precontrol, the reanalysis of hurs  is --- (command line picture included).
Also getting error "relative humidity sfc not available neither directly nor indirectly"
Kindly explain how to sort it.
![![reanalysis](https://user-images.githubusercontent.com/6359243/205442995-21160935-9ecd-40f5-92ed-31a18b6bf0a6.png)
![command](https://user-images.githubusercontent.com/6359243/205443281-0a1c674d-12d3-46db-9ec7-47b3fc2f9485.png)
![domain](https://user-images.githubusercontent.com/6359243/205442990-dcf9d76a-52f1-4700-9cde-7ece7ebb47ad.png)
![model](https://user-images.githubusercontent.com/6359243/205442992-6c4e9d88-676f-4427-8835-5381892df6b7.png)

**Comment by ahernanzl** [comment]
Hello,
Apparently everything is correctly defined. Please, edit the lib/aux_lib.py file. Go to line 100-102 and copy aux=read.one_direct_predictor(var) right before the 'try'. That should print more info about the error while reading the hurs file from reanalysis. You just need to run the PRECONTROL experiment and the 'Check units' step

**Comment by ahernanzl** [comment]
By the way, ERA5 has no hurs, so I guess you have generated it from t2m and d2m, right? Inside the netCDF file, the variable name must be the same that in the filename, just in case. And if you download d2m, pyClim-SDM can retrieve hurs from t2m and d2m

**Comment by geethar123** [comment]
> By the way, ERA5 has no hurs, so I guess you have generated it from t2m and d2m, right? Inside the netCDF file, the variable name must be the same that in the filename, just in case. And if you download d2m, pyClim-SDM can retrieve hurs from t2m and d2m

Yes sir, I have processed the hurs ERA5 data and final processed data is included as hurs_ERA5.....nc file in reanalysis folder.

**Comment by geethar123** [comment]
> By the way, ERA5 has no hurs, so I guess you have generated it from t2m and d2m, right? Inside the netCDF file, the variable name must be the same that in the filename, just in case. And if you download d2m, pyClim-SDM can retrieve hurs from t2m and d2m

I have tried the same steps as you have mentioned. But the result is same. My guess is that the model does not takes reanalysis data of relative humidity, even hurs is mentioned in the domain tab.

Also, my another query is that: what is hur in model then. Will it not be used for downscaling relative humidity.

**Comment by ahernanzl** [comment]
Hi,
Hur is relative humidity on pressure levels and hurs at surface. In order to help you use hurs as direct predictor I need you to see what happens when you copy the reading line out of the 'try'. That file is not being read correctly.
An alternative is to provide d2m so hurs is retrieved indirectly

**Comment by SathyaK2022** [comment]
Hi, iam using pyclim-sdm-version 7 for statistical downscaling of precipitation for a larger domain. My hres_metadata contains 161 ×143  lon- lat points.  GCM Model, ERA5 reanalysis data contains 62×56 lon-lat points for historical period 1985 to 2014 and  for future  scenario SSP245 (2015 to 2100 ). i have been using12TB workstation with 32GB RAM to execute the model. Also,i have tried executing pyclim-sdm in cent-os  and windows subsystem for linux(Ubuntu) at separate workstations.

During precontrol execution, i have been encountered with **ArrayMemoryError: Unable to allocate 14.5 GiB for an array with shape (10957, 57, 52, 60) and data type float64ArrayMemoryError: Unable to allocate 14.5 GiB for an array with shape (10957, 57, 52, 60) and data type float64** in the Cent-OS Workstation. 
In the Ubuntu subsystem, the process gets killed in precontrol step. Could you help me out to solve this issue?
![pyclim_arraymemoryerror](https://github.com/ahernanzl/pyClim-SDM/assets/103311540/349fa1a0-c872-4c9c-b00d-69418f1e23c3)
![Process_Killed_at Precontrol step](https://github.com/ahernanzl/pyClim-SDM/assets/103311540/6e32afe0-4d5b-4553-96fb-ec5f9967163d)

**Comment by ahernanzl** [comment]
Dear user, 
in order to avoid memory problems you could either decrease the number of predictors or the spatial domain (lat/lon). Please, next time open a new issue with a descriptive title. This memory issue has nothing to do with the current title 'variable h in p_hres_metadata and t_hres_metadata', so the explanations is invisible for other users with similar problems.
Thanks
