### ISSUE TITLE
Error in down_scene_RAW.py

### ISSUE THREAD

**Issue by leiapauline** [ahernanzl/pyClim-SDM#40]
I am trying to downscale ERA5 data to particular stations but I am encountering an error. May I request your guidance on resolving it?

```
--------------------------------------
collect chunks 1
tasmax RAW TESTING reanalysis
--------------------
ichunk:	 0 / 1
downscaling tasmax RAW TESTING reanalysis 0.0 %
Traceback (most recent call last):
  File "/home/ltonga/workdir/pyClim-SDM/src/.tmp_main.py", line 15, in <module>
    main()
  File "/home/ltonga/workdir/pyClim-SDM/src/.tmp_main.py", line 11, in main
    process.downscale()
  File "/home/ltonga/workdir/pyClim-SDM/src/../lib/process.py", line 182, in downscale
    reanalisys(method_dict, scene, model)
  File "/home/ltonga/workdir/pyClim-SDM/src/../lib/process.py", line 56, in reanalisys
    down_scene_RAW.downscale_chunk(targetVar, methodName, family, mode, fields, scene, model)
  File "/home/ltonga/workdir/pyClim-SDM/src/../lib/down_scene_RAW.py", line 126, in downscale_chunk
    est[:, ipoint_local_index] = 100 * X_test[:, 0] # Factor 100 is for coherency with other methods
    ~~~^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (1096,) into shape (7305,)

```
Thank you very much. Please let me know if additional information about my input files are needed.

**Comment by ahernanzl** [comment]
Dear leiapauline, 
could you please upload screenshots of your selection at tabs 'Experiment and steps' and 'Dates'? And also of the content (filenames) on your input_data subdirectories?
Thanks

**Comment by leiapauline** [comment]
Hello,
Thank you for your response. Below are the screenshots.
![Screenshot from 2024-03-12 16-57-12](https://github.com/ahernanzl/pyClim-SDM/assets/132651303/5b531554-6a76-4537-89d1-4dc4243064c5)
![Screenshot from 2024-03-12 16-57-25](https://github.com/ahernanzl/pyClim-SDM/assets/132651303/201be94a-0c87-406e-abfc-30a96df3eacc)
![Screenshot from 2024-03-12 16-59-29](https://github.com/ahernanzl/pyClim-SDM/assets/132651303/fe01c1cb-14dd-48e0-87fa-5b98b683268c)

**Comment by ahernanzl** [comment]
I see. The longest period covered by both observations (hres) and reanalysis is 1986-2005, so the selected 'calibration years' must be contained inside this period. Additionally, the selected testing years must be contained inside the calibration period. My suggestion is to select 1986-2005 for the calibration years and 2000-2005 as testing years. Hope it works! Please confirm

**Comment by leiapauline** [comment]
Hello, this is to confirm that it works. Thanks for your guidance.
