### ISSUE TITLE
Error while running the model using my own prepared data

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#43]
The last line said that it could not broadcast input array from shape (60, 45, 43) into shape (1827, 45, 43).I am a freshman. I don't know what's happening and what should I do to make it not happen again.
![屏幕截图 2024-05-07 125643](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/74495aaa-3d0b-422a-b2a1-c513cbe383d5)

**Comment by ahernanzl** [comment]
Dear user,
Can you check that there are no inconsistencies between the years contained at your input data and the years you have selected?
You can find some indications both in the user manual and when passing the mouse over the dates.
Please confirm if the problem is solved.
Kind regards,
Alfonso

**Comment by wonr469** [comment]
Dear Alfonso,
My testing hres dataset dates from 1980 to 1984. My models date from 1950 to 2014 for historical. My reanalysis data dates from 1979 to 2020. My calibration years and reference years set from 1980 to 1984. The time is short, so I choose k-fold to define how to split the calibration period for training/testing.

**Comment by wonr469** [comment]
![屏幕截图 2024-05-08 112451](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/67154429-4485-4a25-b860-15bfd1fdab9b)

**Comment by wonr469** [comment]
NEW error:  TypeError: can only concatenate str (not "list") to str

**Comment by ahernanzl** [comment]
Dear user, 
your dates selection seems consistent with your files. We have updated the software, try the new version and report if the problems remain, please. 
Nevertheless, I need to warn you that statistical downscaling calibrating with only 5 years is not advisable at all. For real applications at least 30 should be use, otherwise the projections will not be very reliable...
Kind regards, 
Alfonso

**Comment by wonr469** [comment]
Dear Alfonso,
I have changed my calibration data to at least 30 years but new problems happen called "domain at netcdf files do not fully contain domain at hres files".
Kind regards,
User

**Comment by wonr469** [comment]
New calibration data dates from 1980 to 2014, 35 years.

**Comment by ahernanzl** [comment]
Hello, 
Apparently you need to cover a larger domain with your netCDF files (renalysis and/or models). Is that so?

**Comment by wonr469** [comment]
The domain of netCDF file is 1980-2014, the same as the calibration dataset. The spatial range is a bit larger than the calibration dataset.

**Comment by wonr469** [comment]
Shall I make reanalysis netcdf file date starts at 1950 instead of 1980?

**Comment by ahernanzl** [comment]
No, the problem is the spatial domain. You need to cover the hres domain with your netCDFs, and with a gridbox additional border

**Comment by wonr469** [comment]
Sir, my hres spatial domain covers 92.2E - 102.2E, 32.25N - 36.4N; my models and reanalysis spatial domain include 91.5E - 103E, 31N - 37N.

**Comment by wonr469** [comment]
Should I extend the spatial range of models and reanalysis? In the condition that the Grid (DD) is 0.25°×0.25°

**Comment by ahernanzl** [comment]
Hello, 
apparently your spatial domains are consistent. Let's do some checks to understand what is going on.
Edit the config/advanced_settings.py file, inserting the following prints around line 764:
if lres_max_lat < hres_max_lat or lres_min_lat > hres_min_lat or lres_max_lon < hres_max_lon or lres_min_lon > hres_min_lon:
    print(lres_max_lat, lres_min_lat, lres_max_lon, lres_min_lon)
    print(hres_max_lat, hres_min_lat, hres_max_lon, hres_min_lon)
    print('Domain at netCDF files do not fully contain domain at hres files. Please check your input files.')
    exit()

**Comment by wonr469** [comment]
Sorry to disturb,
Good news. After inputting the prints you required, I can open gui_mode.py again. Then I make settings in the following graphs:
![屏幕截图 2024-05-23 211642](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/2c75aed0-e6c6-4c84-8df0-c94e64e2916c)
![屏幕截图 2024-05-23 211706](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/a5d709c6-cd43-46c5-9b72-ffda2c196ac7)
![屏幕截图 2024-05-23 211726](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/5655bdb5-61c6-4e06-a2d3-2da38753f40d)
![屏幕截图 2024-05-23 211803](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/416d29d3-bf33-413f-8556-ec63368999eb)
![屏幕截图 2024-05-23 212250](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/e2476927-89fd-4159-bfbd-37300770bdc2)
Saf_lat_up and saf_lon_left are forced. A new error happened called " could not broadcast input array from shape (12784, 21, 45) into shape (12784, 22, 45).

**Comment by ahernanzl** [comment]
Hello,
You are selecting a synoptic domain that dos not cover an extra gridbox to the north (37°). Try changing that, and first delete the config/settings.py file just in case.
I'll be awaiting for your confirmation

**Comment by wonr469** [comment]
Sir, do you mean that a smaller synoptic domain should be covered like that?
![屏幕截图 2024-05-23 232358](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/ee959201-2580-4e96-b026-38ec736a9c24)

**Comment by wonr469** [comment]
Here is what happening
[operation0523.txt](https://github.com/ahernanzl/pyClim-SDM/files/15419253/operation0523.txt)

**Comment by ahernanzl** [comment]
I see. There is a problem when reading the models netCDFs. Other users had the same problem because their models and the reanalysis didn't share the same grid. Is that your case?
See this issue, it might help:
https://github.com/ahernanzl/pyClim-SDM/issues/44

**Comment by wonr469** [comment]
Sir, thanks for your guidance. I'm sorry but still have some problems make me confused.
1. how can I get the detailed content of your input data folders, that have the same format as the #44 Questioner provide?
2. after I add the order "print(targetVar, pred, level, model, scene)", it printed "pr pr None ACCESS-CM2_r1i1p1f1 historical"
3. what I'm confused is that how can he make a missing_data_check and find IndexError: index 0 is out of bounds for axis 0 with size 0?

**Comment by ahernanzl** [comment]
Hello, 
edit file lib/read.py, copying lines 282-283 before the 'try' at line 281 so we can see the error. Also, edit line 142, ading a line with a print(lats) sentence, please. 
Are you sure your models and reanalysis share the same grid?

**Comment by wonr469** [comment]
1. if my model and reanalysis grid is different, what sentence should I add to my python files?
2. I add my read.py sentence at line 142 about printing lres and hres. I update my python document including lib/(1)read.py, (2)MOS_lib.py, (3)WG_lib.py and (4)precontrol.py. Error still exists.
This is the newest operation. Apologies for my poor English and programming abilities.
[operation0527.txt](https://github.com/ahernanzl/pyClim-SDM/files/15453161/operation0527.txt)

**Comment by ahernanzl** [comment]
If your reanalysis and models grids are different there is nothing pyClim-SDM can do. You need to prepare your input_data again, remapping all netCDFs to the same grid. Are your reanalysis and models grids the same or different?

**Comment by wonr469** [comment]
Confirm: if my reanalysis data grid resolution is 0.25°×0.25°, does my model data grid resolution need 0.25°×0.25° too?

**Comment by ahernanzl** [comment]
Yes. You need to remap all files to the same grid, downscaling models or upscaling reanalysis. cdo might help you (https://code.mpimet.mpg.de/projects/cdo)

**Comment by wonr469** [comment]
Q: remap all files to the same grid means different files must have the same grid resolution, or every single grid in different files must match the same range of location in latitude and longitude?

**Comment by ahernanzl** [comment]
All netCDF files must contain the same gridpoints

**Comment by wonr469** [comment]
I see. Thanks.

**Comment by wonr469** [comment]
Dear Alfonso, cdo remap problem occurred, do you know why this happen?
[cdo0612.txt](https://github.com/user-attachments/files/15806056/cdo0612.txt)
![屏幕截图 2024-06-12 214659](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/227a5fd8-a46e-4f8e-8f31-1c2b691069a6)

**Comment by ahernanzl** [comment]
Try removing the blank space after remapbil,
Did it work?

**Comment by wonr469** [comment]
Solve it. Thank you for answering my somewhat basic question. You've been a great help.

**Comment by wonr469** [comment]
Dear Alfonso,
missing_data_check...
ERROR retrieving dates from netCDF models files
Make sure your input_data/models directory contains the needed files.
At least one direct predictors is needed, not only derived predictors.
![屏幕截图 2024-06-13 180601](https://github.com/ahernanzl/pyClim-SDM/assets/169145025/53b59749-41e9-4819-a8bd-3f988c5ccd36)
So what kind of change should i make for my model data?

**Comment by ahernanzl** [comment]
> Hello, 
> edit file lib/read.py, copying lines 282-283 before the 'try' at line 281 so we can see the error. Also, edit line 142, ading a line with a print(lats) sentence, please. 
> Are you sure your models and reanalysis share the same grid?

**Comment by wonr469** [comment]
Sir, my read.py document from line 281-292 is:
 try:
                dates = np.ndarray.tolist(
                    read.one_direct_predictor(pred, level=level, grid='ext', model=model, scene=scene)['times'])
                datesDefined = True
                break
            except:
                pass
        if datesDefined == False:
            print('ERROR retrieving dates from netCDF models files')
            print('Make sure your input_data/models directory contains the needed files.')
            print('At least one direct predictors is needed, not only derived predictors.')
            exit()
For line 142, it has changed to :
 if (lats[0] < lats[-1]) and (np.ndim(data) > 2):
        print(lres_max_lat, lres_min_lat, lres_max_lon, lres_min_lon)
        print(hres_max_lat, hres_min_lat, hres_max_lon, hres_min_lon)
        lats = np.flip(lats)
        data = np.flip(data, axis=1)
Before the problem occurred, it printed:
pred pr get_mean_and_std_reanalysis
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
spred pr get_mean_and_std_reanalysis
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
saf pr get_mean_and_std_reanalysis
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
37.0 31.0 103.0 91.5
36.27 32.33 102.02 92.44
The range of each part:
hres: 92.44°E-102.02°E, 32.33°N-36.27°N；
models: 91.5°E-103.25°E, 31°N-37.25°N, 0.25°×0.25° resolution;
reanalysis: 90.9375°E-105.9375°E, 30.625°N-39.375°N, 0.25°×0.25° resolution with the help of cdo
[Operation0613.txt](https://github.com/user-attachments/files/15820775/Operation0613.txt)

**Comment by ahernanzl** [comment]
models: 91.5°E-103.25°E, 31°N-37.25°N, 0.25°×0.25° resolution;
reanalysis: 90.9375°E-105.9375°E, 30.625°N-39.375°N, 0.25°×0.25° resolution

If I understand correctly, models and reanalysis do not share the same grid. You need to project (cdo remapbil) your models to the reanalysis grid

**Comment by wonr469** [comment]
Modification:
reanalysis: 91.5°E-103.25°E, 31°N-37.25°N, 0.25°×0.25° resolution;
models: 90.9375°E-105.9375°E, 30.625°N-39.375°N, 0.25°×0.25° resolution
Sir, the model and reanalysis grid resolution is the same. The spatial range of models is a little larger than reanalysis. Originally, the models grid resolution was 1.875°×1.25°, but i use remapbil to make models grid resolution the same as the reanalysis one.

**Comment by ahernanzl** [comment]
> All netCDF files must contain the same gridpoints

Let's take 90.9375°E (models left border) and add 0.25° jumping from gridpoint to gridppoint. You'll never fall exactly in the reanalyisis gridpoint 91.5°E.

Is it clear this way?

**Comment by wonr469** [comment]
I got it, let me think about what should i do later. Thank you for your great help.

**Comment by wonr469** [comment]
Sir, new occurs keep coming. I have tried my best to to project (cdo remapbil) my models to the reanalysis grid, and add 0.25° jumping from gridpoint to gridppoint. But it still didn't  work.
[Operation0704.txt](https://github.com/user-attachments/files/16096042/Operation0704.txt)

ValueError: could not broadcast input array from shape (12419,21,0) into shape (12784,21,43)
(base) node04@node04:~/Desktop/pyClim-SDM-master/input_data/models$ cdo griddes pr_ACCESS-CM2_historical_r1i1p1f1_19500101-20141231.nc
#
# gridID 1
#
gridtype  = lonlat
gridsize  = 2100
xsize     = 60
ysize     = 35
xname     = lon
xlongname = "Longitude"
xunits    = "degrees_east"
yname     = lat
ylongname = "Latitude"
yunits    = "degrees_north"
xfirst    = 90.9375
xinc      = 0.25
yfirst    = 30.625
yinc      = 0.25
scanningMode = 0
cdo    griddes: Processed 1 variable [8.65s 64MB]
(base) node04@node04:~/Desktop/pyClim-SDM-master/input_data/models$ cdo griddes pr_ACCESS-CM2_ssp245_r1i1p1f1_20150101-21001231.nc
#
# gridID 1
#
gridtype  = lonlat
gridsize  = 2100
xsize     = 60
ysize     = 35
xname     = lon
xlongname = "Longitude"
xunits    = "degrees_east"
yname     = lat
ylongname = "Latitude"
yunits    = "degrees_north"
xfirst    = 90.9375
xinc      = 0.25
yfirst    = 30.625
yinc      = 0.25
scanningMode = 0
cdo    griddes: Processed 1 variable [92.41s 70MB]
(base) node04@node04:~/Desktop/pyClim-SDM-master/input_data/models$ cd /home/node04/Desktop/pyClim-SDM-master/input_data/reanalysis
(base) node04@node04:~/Desktop/pyClim-SDM-master/input_data/reanalysis$ cdo griddes tp_ERA5_19800101-20141231.nc
#
# gridID 1
#
gridtype  = lonlat
gridsize  = 2079
datatype  = float
xsize     = 63
ysize     = 33
xname     = longitude
xlongname = "longitude"
xunits    = "degrees_east"
yname     = latitude
ylongname = "latitude"
yunits    = "degrees_north"
xfirst    = 90.687
xinc      = 0.2500162
yfirst    = 39.625
yinc      = -0.25
scanningMode = 0
cdo    griddes: Processed 1 variable [1.45s 50MB]

**Comment by ahernanzl** [comment]
Hello, 
I see that the reanalysis and models still don't have the same grid. If you have problems with cdo there are decicated forums, or maybe you know any other tool to do the task.

**Comment by wonr469** [comment]
Progress updated. I checked the attribute of models and reanalysis documents. Here it is.
`Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in <module>
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 9, in main
    preprocess.preprocess()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 43, in preprocess
    common()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 68, in common
    standardization.get_mean_and_std_reanalysis(targetVar, fields_and_grid)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/standardization.py", line 67, in get_mean_and_std_reanalysis
    data = read.lres_data(targetVar, field=field, grid=grid)['data']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 358, in lres_data
    data[i] = one_direct_predictor('pr', level=None, grid='ext', model=model, scene=scene)['data'][idates];
ValueError: could not broadcast input array from shape (12784,21,0) into shape (12784,21,43)
>>> import netCDF4 as nc
>>> fn = 'pr_ACCESS-CM2_historical_r1i1p1f1_19500101-20141231.nc'
>>> ds = nc.Dataset(fn)
>>> print(ds)
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 2.2.3 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.7 CMIP-6.2
    source: ACCESS-CM2 (2019): 
aerosol: UKCA-GLOMAP-mode
atmos: MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)
atmosChem: none
land: CABLE2.5
landIce: none
ocean: ACCESS-OM2 (GFDL-MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)
ocnBgchem: none
seaIce: CICE5.1.2 (same grid as ocean)
    institution: CSIRO (Commonwealth Scientific and Industrial Research Organisation, Aspendale, Victoria 3195, Australia), ARCCSS (Australian Research Council Centre of Excellence for Climate System Science)
    activity_id: CMIP
    branch_method: standard
    branch_time_in_child: 0.0
    branch_time_in_parent: 0.0
    creation_date: 2019-11-09T02:20:30Z
    data_specs_version: 01.00.30
    experiment: all-forcing simulation of the recent past
    experiment_id: historical
    external_variables: areacella
    forcing_index: 1
    frequency: day
    further_info_url: https://furtherinfo.es-doc.org/CMIP6.CSIRO-ARCCSS.ACCESS-CM2.historical.none.r1i1p1f1
    grid: native atmosphere N96 grid (144x192 latxlon)
    grid_label: gn
    history: Thu Jun 13 10:26:34 2024: cdo remapbil,docu01.txt input.nc output.nc
2019-11-09T02:20:30Z ; CMOR rewrote data to be consistent with CMIP6, CF-1.7 CMIP-6.2 and CF standards.
    initialization_index: 1
    institution_id: CSIRO-ARCCSS
    mip_era: CMIP6
    nominal_resolution: 250 km
    notes: Exp: CM2-historical; Local ID: bj594; Variable: pr (['fld_s05i216'])
    parent_activity_id: CMIP
    parent_experiment_id: piControl
    parent_mip_era: CMIP6
    parent_source_id: ACCESS-CM2
    parent_time_units: days since 0950-01-01
    parent_variant_label: r1i1p1f1
    physics_index: 1
    product: model-output
    realization_index: 1
    realm: atmos
    run_variant: forcing: GHG, Oz, SA, Sl, Vl, BC, OC, (GHG = CO2, N2O, CH4, CFC11, CFC12, CFC113, HCFC22, HFC125, HFC134a)
    source_id: ACCESS-CM2
    source_type: AOGCM
    sub_experiment: none
    sub_experiment_id: none
    table_id: day
    table_info: Creation Date:(30 April 2019) MD5:e14f55f257cceafb2523e41244962371
    title: ACCESS-CM2 output prepared for CMIP6
    variable_id: pr
    variant_label: r1i1p1f1
    version: v20191108
    cmor_version: 3.4.0
    tracking_id: hdl:21.14100/27a2a033-bc7e-45ff-8c30-02bf65722aaf
    license: CMIP6 model data produced by CSIRO is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License (https://creativecommons.org/licenses/).  Consult https://pcmdi.llnl.gov/CMIP6/TermsOfUse for terms of use governing CMIP6 output, including citation requirements and proper acknowledgment.  Further information about this data, including some limitations, can be found via the further_info_url (recorded as a global attribute in this file).  The data producers and data providers make no warranty, either express or implied, including, but not limited to, warranties of merchantability and fitness for a particular purpose. All liabilities arising from the supply of the information (including any liability arising in negligence) are excluded to the fullest extent permitted by law.
    CDO: Climate Data Operators version 2.2.1 (https://mpimet.mpg.de/cdo)
    dimensions(sizes): time(23741), bnds(2), lon(60), lat(35)
    variables(dimensions): float64 time(time), float64 time_bnds(time, bnds), float64 lon(lon), float64 lat(lat), float32 pr(time, lat, lon)
    groups: 
>>> fn = '/home/node04/Desktop/pyClim-SDM-master/input_data/reanalysis/tp_ERA5_19800101-20141231.nc'
>>> ds = nc.Dataset(fn)
>>> print(ds)
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    CDI: Climate Data Interface version 2.2.3 (https://mpimet.mpg.de/cdi)
    Conventions: CF-1.6
    history: Sun Jul 07 23:54:05 2024: cdo daysum mertp1980.nc tpsum1980.nc
2024-07-04 09:20:45 GMT by grib_to_netcdf-2.28.1: /opt/ecmwf/mars-client/bin/grib_to_netcdf -S param -o /cache/data4/adaptor.mars.internal-1720084818.869458-19807-1-8b2b23f7-84df-464d-ba58-373bf65a694e.nc /cache/tmp/8b2b23f7-84df-464d-ba58-373bf65a694e-adaptor.mars.internal-1720084168.613236-19807-1-tmp.grib
    frequency: day
    CDO: Climate Data Operators version 2.2.1 (https://mpimet.mpg.de/cdo)
    dimensions(sizes): time(12784), bnds(2), longitude(63), latitude(39)
    variables(dimensions): int32 time(time), int64 time_bnds(time, bnds), float32 longitude(longitude), float32 latitude(latitude), float32 tp(time, latitude, longitude)

`
Is there anyone knows that how to make these documents have the same array shape. Comments are warmly welcomed.

**Comment by ahernanzl** [comment]
Dear user, 
you can use CDO (https://code.mpimet.mpg.de/projects/cdo) to remap your files so both reanalysis and models share the exact same grid. Let's say you want to remap your models to the reanalysis grid. Then you just have to use the following CDO command:
cdo remapbil,reanalysis_file.nc model_file.nc out.nc

Be aware that there is no blank space after 'remapbil,'
Hope it helps!

**Comment by wonr469** [comment]
There is a question. When I download models document, its longitude unit looks like:
90.9375E, 92.8125E, ..., 104.0625E, 105.9375E. (1.875° interval)
reanalysis longitude unit looks like:
89.062E, 90.9371E, 92.8122E, ..., 104.0628E, 105.9379E, 107.813E, 109.6881E. (1.8751° interval)
If there is only 0.0001°interval error, is your PyClim software can accept it and operate smoothly?

**Comment by wonr469** [comment]
ERROR retrieving dates from netCDF reanalysis files
At least one direct predictors is needed, not only derived predictors.
Is that mean  there are at least two documents in different types needed in the reanalysis file ?

**Comment by ahernanzl** [comment]
What predictors are you selecting?

**Comment by wonr469** [comment]
pr. You mean I should select more than one predictor?

**Comment by wonr469** [comment]
btw, respectful Mr Alfonso, may I know your email address so that I can reponse, and ask question more promptly?

**Comment by ahernanzl** [comment]
That error comes from lines 302-328 of lib/read.py. Those lines are meant to retrieve dates from netCDF reanalysis files, but something is going wrong. In order to find out what it is, you will need to modify the code and see what happens.
Please copy this two lines of code after line 303: 

_aux_times = one_direct_predictor(var, grid='ext', model=model, scene=scene)['times']
print(aux_times)_

and select only precipitation as target variable and as only predictor. Then tell us what you get.
And about the email, I rather keep communicating as issues, so it can help other users and because I am not the only one answering

Kind regards

**Comment by wonr469** [comment]
Respectful Alfonso,
I have copied this two lines of code you mentioned after line 303. Here is the response.
`Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in &lt;module&gt;
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 9, in main
    preprocess.preprocess()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 43, in preprocess
    common()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 68, in common
    standardization.get_mean_and_std_reanalysis(targetVar, fields_and_grid)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/standardization.py", line 67, in get_mean_and_std_reanalysis
    data = read.lres_data(targetVar, field=field, grid=grid)['data']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 305, in lres_data
    aux_times = one_direct_predictor(var, grid='ext', model=model, scene=scene)['times']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 201, in one_direct_predictor
    nc = netCDF(pathIn, filename, ncVar, grid=grid, level=level)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 81, in netCDF
    calendar = nc.variables[time_name].calendar
KeyError: 'time'`

**Comment by ahernanzl** [comment]
Ok, for some reason the netCDF reanalysis file hasn't got a time variable named 'time'. Let's see if the time variable is named with any other name. For this purpose, edit the same file, uncommenting lines 55-60 and show me what happens

**Comment by wonr469** [comment]
Hello Mr Alfonso,
I have uncommented lines 55-60, and here is the result. My apologies of bothering you.
(base) node04@node04:~/Documents/0828NewCollect/tpreanalysis$ cdo sinfo tp_ERA5_19800101-20141231.nc
   File format : NetCDF4
    -1 : Institut Source   T Steptype Levels Num    Points Num Dtype : Parameter ID
     1 : ECMWF    unknown  v instant       1   1       336   1  F32  : -1            
   Grid coordinates :
     1 : lonlat                   : points=336 (24x14)
                              lon : 86 to 109 by 1 degrees_east
                              lat : 42 to 29 by -1 degrees_north
   Vertical coordinates :
     1 : surface                  : levels=1
   Time coordinate :
                       valid_time : 12784 steps
     RefTime =  1970-01-01 00:00:00  Units = seconds  Calendar = proleptic_gregorian  Bounds = true
  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss  YYYY-MM-DD hh:mm:ss
cdo    sinfo: Processed 1 variable over 12784 timesteps [1.05s 50MB]


(env) node04@node04:~/Desktop/pyClim-SDM-master/src$ python3 gui_mode.py
---------------------------------------------------------------
CAUTION: predictors will be standardized, and precipitation should not be mixed with other predictors and used that way.
Standardizing precipitation will lead to zeros being represented by different values depending on the model.
This is not advisable and can lead to poor performance of Transfer Function methods.
---------------------------------------------------------------
---------------------------------------------------------------
CAUTION: predictors will be standardized, and precipitation should not be mixed with other predictors and used that way.
Standardizing precipitation will lead to zeros being represented by different values depending on the model.
This is not advisable and can lead to poor performance of Transfer Function methods.
---------------------------------------------------------------
grids.association() starts
pr grids.association nearest 0.0 %
grids.association() starts
pr grids.association bilinear 0.0 %
pred pr get_mean_and_std_reanalysis
Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in <module>
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 9, in main
    preprocess.preprocess()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 43, in preprocess
    common()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 68, in common
    standardization.get_mean_and_std_reanalysis(targetVar, fields_and_grid)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/standardization.py", line 67, in get_mean_and_std_reanalysis
    data = read.lres_data(targetVar, field=field, grid=grid)['data']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 299, in lres_data
    aux_times = one_direct_predictor(var, grid='ext', model=model, scene=scene)['times']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 195, in one_direct_predictor
    nc = netCDF(pathIn, filename, ncVar, grid=grid, level=level)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 75, in netCDF
    calendar = nc.variables[time_name].calendar
KeyError: 'time'

**Comment by ahernanzl** [comment]
Have you uncommented these lines?

    # for var in nc.variables:
    # 	print('----------------------------')
    # 	print(var)
    # 	print(nc.variables[var])
    # 	# print(nc.variables[var][:])
    # 	print(nc.variables[var][:].shape)

**Comment by wonr469** [comment]
I have uncommented these lines.

**Comment by ahernanzl** [comment]
Well, I do not understand. 
For your comments I see that line 75 is beeing executed: 
_File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 75, in netCDF
calendar = nc.variables[time_name].calendar_

But I do not see the information from the prints in lines 55-60.
Is it possible that the netCDF file does not contain any variable at all?!

Uncomment also lines 54 and 61 please.

**Comment by wonr469** [comment]
Hello, let me think about why this is, if there is no solution I will leave a message here. I'll uncomment lines 54 and 61.

**Comment by wonr469** [comment]
Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in &lt;module&gt;
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 10, in main
    preprocess.train_methods()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 200, in train_methods
    TF_lib.train_chunk(targetVar, methodName, family, mode, fields)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/TF_lib.py", line 77, in train_chunk
    y_train = read.hres_data(targetVar, period='training')['data']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 706, in hres_data
    aux_lib.prepare_hres_data_ascii2npy(targetVar)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/aux_lib.py", line 216, in prepare_hres_data_ascii2npy
    year = int(str(int(float(line[0])))[:4])
ValueError: could not convert string to float: '19800101\t0.00'


Last problem solved. By changing words from " time_name = 'time'" to" time_name = 'valid_time'", according to my reanalysis document. How about this issue shown above? What changes should I make for words in  "/home/node04/Desktop/pyClim-SDM-master/src/../lib/aux_lib.py".

**Comment by ahernanzl** [comment]
Hi, 
it appears that your hres file fields are separated by \t instead of white spaces. You can either modify your file or change line 209 of lib/aux_lib.py file

**Comment by wonr469** [comment]
Sir, if this error happens,
`File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/aux_lib.py", line 219, in prepare_hres_data_ascii2npy
    data = np.append(data, np.asanyarray(line, dtype=float), axis=0)
ValueError: could not convert string to float: '/'`

What should I modify for the following part? 
`if year in range(minYear, maxYear+1):
            # Appends line to array
            data = np.append(data, np.asanyarray(line, dtype=float), axis=0)
            # Cut in chunks
            if (i % 100 == 0) or (i == (num_lines - 1)):
                print('read.hres_data', filename, i, '/', num_lines, 100 * i / num_lines, '%')
                np.save(tmp + 'chunk' + str(chunk), data)
                chunk += 1
                data = np.zeros((0))
    f.close()`

**Comment by wonr469** [comment]
Here is my precipitation data
[pr_19800101-20141231.txt](https://github.com/user-attachments/files/16860481/pr_19800101-20141231.txt)
Addition for operating process and error occurred.
`
read.hres_data ../input_data/hres/pr_19800101-20141231 1500 / 12784 11.733416770963705 %
Traceback (most recent call last):
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 18, in &lt;module&gt;
    main()
  File "/home/node04/Desktop/pyClim-SDM-master/src/.tmp_main.py", line 10, in main
    preprocess.train_methods()
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/preprocess.py", line 200, in train_methods
    TF_lib.train_chunk(targetVar, methodName, family, mode, fields)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/TF_lib.py", line 77, in train_chunk
    y_train = read.hres_data(targetVar, period='training')['data']
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/read.py", line 706, in hres_data
    aux_lib.prepare_hres_data_ascii2npy(targetVar)
  File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/aux_lib.py", line 219, in prepare_hres_data_ascii2npy
    data = np.append(data, np.asanyarray(line, dtype=float), axis=0)
ValueError: could not convert string to float: '/'`

**Comment by ahernanzl** [comment]
At line 1513 of your hres file there is a '/' symbol instead of a number. You should change it for a -999, as it is explained in the user_manual included in the doc directory. 
Try that and see if everything works fine

**Comment by wonr469** [comment]
Omm. I'm so sorry. I can run my own data. That's a great help.
