### ISSUE TITLE
Issue regarding to dates in NETCDF

### ISSUE THREAD

**Issue by PaulRaam** [ahernanzl/pyClim-SDM#44]
Hello !

I´ve been modifying the input data, but I still have the same problem during missing data check:

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/7de36b01-1447-4ed6-8086-2089ff2fbae5)

I tryed to understad source scripts, but i'm not sure if problem is regarding to model or reanalysis data.

**Comment by ahernanzl** [comment]
Dear Paul,
Can you provide screenshots of your selection as well as the content of your input data folders?
Kind regards,
Alfonso

**Comment by PaulRaam** [comment]
Dear Alfonso, can we continue the talking in spanish?

screenshots: 
![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/5d0e83d7-f607-486f-951f-143427e1d9d8)

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/b83f9db9-65d5-457a-94da-6c1fc6b95855)

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/e1eaac1c-8e18-4f15-8842-c9c9b5a7ad72)

source metadata (models):
<xarray.Dataset>
Dimensions:    (time: 60265, bnds: 2, lat: 77, lon: 61)
Coordinates:
  * time       (time) float64 0.5 1.5 2.5 3.5 ... 6.026e+04 6.026e+04 6.026e+04
  * lat        (lat) float64 -18.8 -18.5 -18.3 -18.0 ... -0.7 -0.5 -0.2 0.0
  * lon        (lon) float64 -80.6 -80.4 -80.2 -80.0 ... -68.2 -67.9 -67.7 -67.5
Dimensions without coordinates: bnds
Data variables:
    time_bnds  (time, bnds) float64 ...
    lat_bnds   (time, lat, bnds) float64 ...
    lon_bnds   (time, lon, bnds) float64 ...
    pr         (time, lat, lon) float64 ...
Attributes: (12/47)
    Conventions:            CF-1.7 CMIP-6.2
    activity_id:            CMIP
    branch_method:          standard
    branch_time_in_child:   0.0
    branch_time_in_parent:  21915.0
    creation_date:          2019-11-15T17:33:19Z
    ...                     ...
    variable_id:            pr
    variant_label:          r1i1p1f1
    version:                v20191115
    cmor_version:           3.4.0
    tracking_id:            hdl:21.14100/6c93c39c-158b-4585-891e-8e011c7fde01
    license:                CMIP6 model data produced by CSIRO is licensed un...

reanalysis:
<xarray.Dataset>
Dimensions:  (lon: 61, lat: 77, time: 12418)
Coordinates:
  * lon      (lon) float32 -82.0 -81.8 -81.5 -81.2 ... -67.8 -67.5 -67.2 -67.0
  * lat      (lat) float32 -19.0 -18.8 -18.5 -18.2 -18.0 ... -0.8 -0.5 -0.2 -0.0
  * time     (time) int32 788940 788964 788988 ... 1086900 1086924 1086948
Data variables:
    tp       (time, lat, lon) float32 ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-05-13 04:42:50 GMT by grib_to_netcdf-2.28.1: /opt/ecmw...

**Comment by PaulRaam** [comment]
Sorry, I forgot the selection:

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/53d0d943-bcb9-4fdc-a03c-e5b9cdd76f6b)

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/e3bc65b7-ecfa-4f09-b5b4-dd610f8a023e)

![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/9fecfa0c-769d-4baa-b3a0-30d4ef68a30d)

**Comment by ahernanzl** [comment]
Buenas Paul, 
está encontrando un problema en recuperar las fechas de algún modelo, pero no veo nada raro en la información que adjuntas. ¿Es posible que hayas activado alguna variable más además de la precipitación?
Prueba a introducir una línea con el siguiente print adicional en el fichero /lib/read.py (línea 289) y me muestras la salida a ver por dónde podemos indagar:

        if datesDefined == False:
            print(targetVar, pred, level, model, scene)
            print('ERROR retrieving dates from netCDF models files')
            print('Make sure your input_data/models directory contains the needed files.')
            print('At least one direct predictors is needed, not only derived predictors.')
            exit()

Un saludo,
Alfonso

**Comment by PaulRaam** [comment]
Hola Alfonso. 
Antes de cualquier cosa, quisiera agradecer tu ayuda en este asunto, pues llevo días intentando por mi cuenta entender el problema pero no ha sido posible.

Ahora bien, te muestro el print:
pr pr None ACCESS-ESM1-5_r1i1p1f1 historical

Saludos.
Paul

**Comment by ahernanzl** [comment]
Perfecto, falla en el primer modelo. Veamos qué error da. Haz una copia de la linea 282 (la que llama a la funcion de lectura de one_direct_predictor) fuera del try para que nos muestre el error.
Un saludo

**Comment by PaulRaam** [comment]
Claro, el error es el siguiente:

missing_data_check...
Traceback (most recent call last):
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 17, in <module>
    main()
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 11, in main
    precontrol.missing_data_check()
  File "/home/paulraam/pyClim-SDM-master/src/../lib/precontrol.py", line 73, in missing_data_check
    data = read.lres_data(targetVar, 'pred', model=model, scene=sceneName, predName=predName)['data']
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 283, in lres_data
    read.one_direct_predictor(pred, level=level, grid='ext', model=model, scene=scene)['times'])
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 199, in one_direct_predictor
    nc = netCDF(pathIn, filename, ncVar, grid=grid, level=level)
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 141, in netCDF
    if (lats[0] < lats[-1]) and (np.ndim(data) > 2):
  File "/home/paulraam/miniconda3/envs/env_pyClim-SDM/lib/python3.10/site-packages/numpy/ma/core.py", line 3222, in __getitem__
    dout = self.data[indx]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ahernanzl** [comment]
Ok, haz un print antes de la linea 141 de lats y de data, a ver cuál está fallando

**Comment by PaulRaam** [comment]
missing_data_check...
[]
[]
Traceback (most recent call last):
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 17, in <module>
    main()
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 11, in main
    precontrol.missing_data_check()
  File "/home/paulraam/pyClim-SDM-master/src/../lib/precontrol.py", line 73, in missing_data_check
    data = read.lres_data(targetVar, 'pred', model=model, scene=sceneName, predName=predName)['data']
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 286, in lres_data
    read.one_direct_predictor(pred, level=level, grid='ext', model=model, scene=scene)['times'])
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 202, in one_direct_predictor
    nc = netCDF(pathIn, filename, ncVar, grid=grid, level=level)
  File "/home/paulraam/pyClim-SDM-master/src/../lib/read.py", line 144, in netCDF
    if (lats[0] < lats[-1]) and (np.ndim(data) > 2):
  File "/home/paulraam/miniconda3/envs/env_pyClim-SDM/lib/python3.10/site-packages/numpy/ma/core.py", line 3222, in __getitem__
    dout = self.data[indx]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by PaulRaam** [comment]
Alfonso, he logrado resolver el problema. Leyendo todos los issues anteriores, le habias comentado a otro usuario que tanto los models, como los reanalysis debian tener exactamente la misma grilla. He modificado eso y ya no tengo dicho problema ! Ahora mi problema es diferente:

GCMs_evaluation...
{'ANNUAL': range(1, 13), 'DJF': [1, 2, 12], 'MAM': [3, 4, 5], 'JJA': [6, 7, 8], 'SON': [9, 10, 11]}
GCMs_evaluation_historical...
Traceback (most recent call last):
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 17, in <module>
    main()
  File "/home/paulraam/pyClim-SDM-master/src/.tmp_main.py", line 13, in main
    precontrol.GCMs_evaluation()
  File "/home/paulraam/pyClim-SDM-master/src/../lib/precontrol.py", line 1014, in GCMs_evaluation
    GCMs_evaluation_historical()
  File "/home/paulraam/pyClim-SDM-master/src/../lib/precontrol.py", line 321, in GCMs_evaluation_historical
    scene_dates = scene_dates[idates]
TypeError: list indices must be integers or slices, not list

**Comment by ahernanzl** [comment]
Buenas, 
lo he corregido, descarga la nueva versión (solo he cambiado el fichero /lib/precontrol.py), disculpa el bug. 
Saludos,
Alfonso

**Comment by PaulRaam** [comment]
Excelente, ya me funciono todo ! Queria preguntarte una ultima cosa, el modelo entrega las series proyectadas por cada estación (hres) en cada modelo y escenario? o eso no ocurre?

**Comment by ahernanzl** [comment]
Sí, eso es exactamente lo que hace. Además incluye gráficas del ensemble multimodelo, pero los ficheros de datos son para cada modelo y escenario. Espero que sea de utilidad

**Comment by PaulRaam** [comment]
Hola de nuevo Alfonso, te cuento que he logrado hacer el DS de la precipitación y la temperatura media de mi zona. Sin embargo, al intentar hacer el ejercicio con las temperaturas maximas y minimas, aparece el siguiente error:
Traceback (most recent call last):
  File "/home/paulraam/pyClim-SDM-master/src/gui_mode.py", line 36, in <module>
    from imports import *
  File "/home/paulraam/pyClim-SDM-master/src/../config/imports.py", line 79, in <module>
    import ANA_lib
  File "/home/paulraam/pyClim-SDM-master/src/../lib/ANA_lib.py", line 5, in <module>
    from advanced_settings import *
  File "/home/paulraam/pyClim-SDM-master/src/../config/advanced_settings.py", line 417, in <module>
    aux_hres_years = (max([int(hresPeriodFilename[x][:4]) for x in targetVars]), min([int(hresPeriodFilename[x][-8:-4]) for x in targetVars]))
ValueError: max() arg is an empty sequence
los nombres de mis archivos son:
![image](https://github.com/ahernanzl/pyClim-SDM/assets/58944154/9fde4fda-916c-4782-985b-6b2854efe67a)

**Comment by ahernanzl** [comment]
Buenas, ¿y de tasmax tienes también los archivos?

**Comment by PaulRaam** [comment]
Si, los tengo. Pero los saque de la carpeta para poder testear variable por variable.

**Comment by ahernanzl** [comment]
¿Y tienes activada tasmax por un casual?

**Comment by PaulRaam** [comment]
Lo que pasa es que no me deja iniciar el gui_mode.py cuando tengo archivos con nombre tasmin o tasmax en la carpeta hres, por que me salta el error que te puse. le hice un print a hresPeriodFilename antes de la linea 417 y aparece vacio.

**Comment by PaulRaam** [comment]
con los archivos de tasmax puestos en la carpeta hres, agregue prints a targetvars in targetvar (linea 330 del archivo "advanced_settings.py") y me aparece lo siguiente:
['tas'] 
tas 
La primer salida es el print de targetVars, y la segunda de targetVar

**Comment by ahernanzl** [comment]
¿Puede ser que tengas activada la variable tas pero no tasmax ni tasmin? Pasa por las pestañas de las variables y activa/desactiva las que quieras calcular

**Comment by PaulRaam** [comment]
Vale, funciono ! Gracias.
Tuve que cambiar los nombres de los archivos de tasmax a tas, para que entrera el gui_mode, una vez allí prendi y configure la pestaña de tasmax, y antes de darle run, volvi a la carpeta de hres, y les cambie de nuevo el nombre de los archivos a tasmax.

Me da la sencación que hice algo mal y por eso tuve que dar toda esa vuelta ¿alguna idea de que fue?

**Comment by ahernanzl** [comment]
Uf, pues qué raro. Ni idea, pero si te vuelve a ocurrir indagamos para solucionar en caso de error de código.
Un saludo
