### ISSUE TITLE
Issue regarding spatial downscaling

### ISSUE THREAD

**Issue by ccalvosa** [ahernanzl/pyClim-SDM#46]
Buenos días, 

Estoy intentando generar un downscaling de distintos modelos climáticos utilizando el reanálisis ERA5 de forma espacial. He intentado generarlo con los datasets de prueba que hay, pero continuamente obtengo resultados de forma puntual. ¿Cómo sería posible generar un downscaling de forma espacial, es decir, en una malla? 

Gracias y un saludo,

**Comment by ahernanzl** [comment]
Buenos días, 
pyClim-SDM solo trabaja con datos puntuales. Se puede hacer downscaling de una malla regular 2D pasándola a un listado de puntos 1D, y tras el proceso recomponiendo la malla 2D, todo ello por parte del usuario con sus propias herramientas. 
Un saludo
