### ISSUE TITLE
EVALUATION AttributeError 'append'

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#49]
Hello, I have installed new version of pyClim-SDM, which all documents are the same as shown in Github. I'm using your testing data to evaluate. PRECONTROL no problem. However, when comes to EVALUATION, an error occurred.
`AttributeError: 'DataFrame' object has no attribute 'append'`
,from
`File "/home/node04/Desktop/pyClim-SDM-master/src/../lib/grids.py", line 336, in subregions
    df_reg = df_reg.append({'regType': regType, 'regName': regName, 'subDir': subDir, 'ipoints': ipoints}, ignore_index=True)
File "/home/node04/Downloads/miniconda3/envs/env/lib/python3.9/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)`

**Comment by ahernanzl** [comment]
What version of pandas are you using? See the readme.md file, the installation instructions indicate the version supported

**Comment by wonr469** [comment]
I see what the problm is. Thanks a lot.
