### ISSUE TITLE
reanalysis document not detected

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#50]
An error called `ERROR: Variable time not found at reanalysis netCDF` happened so that I can not open my gui_mode. However, there is a tp document exist in my reanalysis file.
![屏幕截图 2024-09-11 150058](https://github.com/user-attachments/assets/2bd7f26f-46a6-4c7e-a24b-46aa11d7ba69)
Because of the attribute of my tp reanalysis document,
![屏幕截图 2024-09-11 145821](https://github.com/user-attachments/assets/0a1ea291-1fb1-480c-9ddd-c0c13a204f95)

I have made changes like what you said in #47 , but the error still happens.
![屏幕截图 2024-09-11 151015](https://github.com/user-attachments/assets/53568e53-b4a7-4aae-ae10-5f4db192b9f4)
![屏幕截图 2024-09-11 150905](https://github.com/user-attachments/assets/0c62d412-a111-479b-8668-b72df8c363ce)

**Comment by ahernanzl** [comment]
I have addapted the config/advanced_settings.py file so it can deal with your netCDFs format. Try it with the new code

**Comment by wonr469** [comment]
OK. Done.
