### ISSUE TITLE
How do I leave only one version of pandas packages in conda?

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#51]
How do I take two different versions of pandas packages that are located in different folders but are both in the conda environment, leaving only one version of them?

I use my python language program and try to operate it in conda env. An error is reported called "AttributeError: 'DataFrame' object has no attribute 'append'". That's because my pandas package is not a matched version for the program. So I required conda uninstall pandas 2.2.2 and conda install pandas 1.4.3. In theory, there is only pandas 1.4.3 left, but now my conda file includes two different pandas versions and they interrupt my program's operation.
The following results and pictures show the condition.
`(env) node04@node04:~/Desktop/pyClim-SDM-master/src$ conda uninstall pandas=2.2.2
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - pandas=2.2.2

(env) node04@node04:~/Desktop/pyClim-SDM-master/src$ conda list pandas
# packages in environment at /home/node04/Downloads/miniconda3/envs/env:
#
# Name                    Version                   Build  Channel
geopandas                 0.14.3                   pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
(env) node04@node04:~/Desktop/pyClim-SDM-master/src$ conda remove --force pandas2.2.2

==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 24.7.1

Please update conda by running

    $ conda update -n base -c conda-forge conda

PackagesNotFoundError: The following packages are missing from the target environment:
  - pandas2.2.2
`
![屏幕截图 2024-09-12 135326](https://github.com/user-attachments/assets/bc6c76d6-cd1e-4fca-a3c0-0eabd1ebcc6c)
![屏幕截图 2024-09-12 135450](https://github.com/user-attachments/assets/8007996d-b3f3-4e94-bc43-dc371014223b)
![屏幕截图 2024-09-12 135744](https://github.com/user-attachments/assets/9bf8f69e-23af-496c-ab22-3b045af5c477)

**Comment by ahernanzl** [comment]
Have you tried creating a new environment from scratch following the installation instructions?

**Comment by wonr469** [comment]
I will reinstall the newest Miniconda and follow the installation instructions.
