### ISSUE TITLE
A tiny question about 

### ISSUE THREAD

**Issue by wonr469** [ahernanzl/pyClim-SDM#52]
After operating and reading the manual, one tiny thing makes me a bit confused. Is the choice of Synoptic Analogy Fields restricted by the type of files in the models folder?

**Comment by ahernanzl** [comment]
Well, if you want to use U500 and V500 as Synoptic Analogy Fields you need those files both for the reanalysis and for the models. Does that answer your question?

**Comment by wonr469** [comment]
That's it. If no one else asks the question additionally, the contributor can close it.
